# opcode constants
# MODES
SAFE_MODE = "131"
FULL_MODE = "132"
# CLEANING
CLEAN = "135"
MAX = "136"
SPOT = "134"
SEEK_DOCK = "143"
POWER_OFF = "133"
# ACTUATOR
DRIVE = "137"
DRIVE_DIRECT = "145"
MOTORS = "138"
LED = "139"
SONG = "140"
# SPECIAL DRIVE VALUES
DRIVE_STRAIGHT_VALUE = 32768
DRIVE_CLOCKWISE_VALUE = -1
DRIVE_COUNTERCLOCKWISE_VALUE = 1
# SPECIAL MOTOR VALUES
SIDEBRUSH_COUNTERCLOCKWISE_VALUE = 0
SIDEBRUSH_CLOCKWISE_VALUE = 3
MAINBRUSH_INWARD_VALUE = 2
MAINBRUSH_OUTWARD_VALUE = 4
VACUUM_VALUE = 1
# INPUT COMMANDS
SENSORS = "142"
QUERY_LIST = "149"
STREAM = "148"
PAUSE_RESUME_STREAM = "150"
# PACKET ID LIST
BUMPS_AND_WHEEL_DROPS = "7"
WALL = "8"
CLIFF_LEFT = "9"
CLIFF_FRONT_LEFT = "10"
CLIFF_FRONT_RIGHT = "11"
CLIFF_RIGHT = "12"
VIRTUAL_WALL = "13"
WHEEL_OVERCURRENTS = "14"
DIRT_DETECT = "15"
INFARED_CHAR_OMNI = "17"
INFARED_CHAR_LEFT = "52"
INFARED_CHAR_RIGHT = "53"
DISTANCE_TRAVELLED = "19"
DEGREES_TURNED = "20"
BATTERY_VOLTAGE_MV = "22"
BATTERY_CURRENT_MA = "23"
BATTERY_TEMPERATURE_CELSIUS = "24"
BATTERY_CHARGE_MAH = "25"
BATTERY_CAPACITY_MAH = "26"
WALL_SIGNAL = "27"
CLIFF_LEFT_SIGNAL = "28"
CLIFF_FRONT_LEFT_SIGNAL = "29"
CLIFF_FRONT_RIGHT_SIGNAL = "30"
CLIFF_RIGHT_SIGNAL = "31"
LIGHT_BUMPER = "45"
LIGHT_BUMPER_LEFT_SIGNAL = "46"
LIGHT_BUMPER_FRONT_LEFT_SIGNAL = "47"
LIGHT_BUMPER_CENTER_LEFT_SIGNAL = "48"
LIGHT_BUMPER_CENTER_RIGHT_SIGNAL = "49"
LIGHT_BUMPER_FRONT_RIGHT_SIGNAL = "50"
LIGHT_BUMPER_RIGHT_SIGNAL = "51"